 const actionTypes ={
    REST_LOADING: "REST_LOADING",
    REST_SUCCESS: "REST_SUCCESS",
    REST_ERROR: "REST_ERROR",
    
    PRODUCT_LOADING: "PRODUCT_LOADING",
    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
    PRODUCT_ERROR: "PRODUCT_ERROR",

    CARD_LOADING:"CARD_LOADING",
    CARD_SUCCESS:"CARD_SUCCESS",
    CARD_ERROR:"CARD_ERROR",
    ADD_TO_CARD:"ADD_TO_CARD",
    DELETE_FROM_CARD:"DELETE_FROM_CARD",
    UPDATE_CARD:"UPDATE_CARD"
}



export default actionTypes;